### PR TITLE
fix: add shims for GOARCH=wasm with GOOS=js and GOOS=wasip1

### PR DESCRIPTION
**Pull request by paralin**
Fixes build errors:

GOOS=js GOARCH=wasm go build
GOOS=wasip1 GOARCH=wasm go build

### CODE REVIEW

**Comment by cmaglie** [comment]
@paralin what's the purpose of this patch? since `nativeOpen` is not implemented the library will not be available on `wasm` anyway.

**Comment by paralin** [comment]
When the library is used as a dependency it is best to have it compile cleanly when that GOOS is used with stubs that return errors instead of failing to build entirely. This is for a dependency of https://github.com/aperturerobotics/bifrost

**Comment by paralin** [comment]
1. They don't use the same build tags. It's GOOS=js GOARCH=wasm and GOOS=wasip1 GOARCH=wasm but only one of these sets the wasm build tag. If the file is named _wasm it won't be built on wasip1 (iirc)
2. That doesn't work quite right from my testing before due to the above.
3. Will do

**Comment by paralin** [comment]
You were right on the build tags, I fixed the PR according to your request.

**Pull request merged**
