### PR TITLE
Works on FreeBSD (even on armv6 and armv7 when cross compiled).

### PR DESCRIPTION
**Pull request by fbettag**
i just copied darwin stuff :)

### CODE REVIEW

**Comment by cmaglie** [comment]
thanks for your conribution @fbettag !

would you like to try also the version listed here https://github.com/bugst/go-serial/tree/v1 ?
I've refactored the API to be more go-lang style, but since this is a breaking change it forced me to change the import from

`go.bug.st/serial`

to

`go.bug.st/serial.v1`

so you can keep both side-by-side.
My plan is to switch development to v1 soon (the old version will be marked `v0` and will continue to be available on the old import).

**Comment by fbettag** [comment]
No problems! I needed it for a side project :)

Well since i just copied _darwin to _freebsd, i’m sure you can do this easier than me forking and opening a PR :P

Thanks for the great library!

**Comment by cmaglie** [comment]
> Well since i just copied _darwin to _freebsd, i’m sure you can do this easier than me forking and opening a PR :P

yes I did it already:

https://github.com/bugst/go-serial/commit/85dc492d831a32c6f0fe4be8762c9a034226eb6e

but I've no freebsd box at hand so my request was just to *test* it :-)

**Comment by fbettag** [comment]
Oh sorry, i’ll give it a shot later today!

**Comment by fbettag** [comment]
Just tested .v1 on FreeBSD 10.3-RELEASE and cross compiled with go 1.7 and GOARM=6 GOARCH=arm GOOS=freebsd and works perfectly :)

**Pull request merged**
